import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import BreadcrumbComponent from "@/components/breadcrumb";
import { redirect } from "next/navigation";
import { userIsLoged } from "@/actions/userActions";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const { sucess } = await userIsLoged();

  if(!sucess)
      return redirect("/login");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="flex flex-col flex-1 pt-2">
            <SidebarTrigger />
            <BreadcrumbComponent />

            <div className="flex flex-1 p-4">
              {children}
            </div>
            <Toaster />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
